### ISSUE TITLE
Payment process not processing at step one

### ISSUE THREAD

**Issue by azbassiouny** [et3egypt/business-service#23]

**Comment by azbassiouny** [comment]
@AhmedFathy16 please check server 81.23

Thanks

**Comment by AhmedFathy16** [comment]
@azbassiouny Ok

**Comment by AhmedFathy16** [comment]
![capture](https://user-images.githubusercontent.com/45422651/50383234-19510500-06b8-11e9-9857-9dabbff91490.JPG)

فيه مشكلة فى السيرفس بتاعة السيكوال  بس دورت عليها فى السيرفسات مش لاقيها
ومش لاقى الكونفجراشن بتاع السيكوال على السيرفر هو فى مكان تانى ولا فيه طريقة معينه ؟؟
@azbassiouny

**Comment by azbassiouny** [comment]
السيكوول مش على نفس الجهاز السيكوول على ٨١،٧٩
بس الريموت بتاعه مش شغال 
بص عالديسكات عن طريق انك تفتح السرفر مانجمنت اللي في ال٢٣ وتكونكت تو انوثر كمبيوتر ودخل اسم الجهاز السيكوول 
auc-s-tmpsql
حتلاقي الديسكات تحت نود الكونفيجريشن
@ahmedfathy16

**Comment by azbassiouny** [comment]
لقيت ايه؟ @AhmedFathy16

**Comment by AhmedFathy16** [comment]
@azbassiouny وصلتلها وشغلتها والبايمنت شغال تمام

**Comment by azbassiouny** [comment]
المشكلة كانت ايه ؟ السرفس واقفة بس؟
@AhmedFathy16

**Comment by AhmedFathy16** [comment]
@azbassiouny 
اه السرفس بتاعة السيكوال كانت واقفه اول ما شغلتها البايمنت اشتغل
بس فيه أوركستراشن معموله ديهايدريتد دلوقتى معرفش ده عادى ولا الشغل واقف كده

**Comment by azbassiouny** [comment]
الديهايدريتد ديه عشان مستنية اليوزر يصبمت الشيت في ستيب 2 
@AhmedFathy16 
ده الطبيعي

**Comment by AhmedFathy16** [comment]
تمام
